import type { SopDocument } from "../types";

const PRODUCTS = [
  "BangTabungan Digital",
  "BangTabungan Rencana",
  "BangTabungan Bisnis",
  "BangGiro Usaha",
  "BangGiro Korporasi",
  "BangDeposito",
  "BangDeposito Valas",
  "BangKartu Debit",
  "BangKartu Classic",
  "BangKartu Gold",
  "BangKartu Platinum",
  "BangPinjam KTA",
  "BangPinjam Usaha",
  "BangKUR",
  "BangKPR",
  "BangKPR Takeover",
  "BangKKB",
  "BangPaylater",
  "BangInvest Pasar Uang",
  "BangInvest Pendapatan Tetap",
  "BangInvest Saham Nusantara",
  "BangInvest Campuran",
  "BangObligasi Negara Ritel",
  "BangProteksi Sejahtera",
  "BangVA Merchant",
] as const;

const SEGMENTS = ["personal", "affluent", "priority", "sme"] as const;

const CITIES = [
  "Jakarta Pusat",
  "Jakarta Selatan",
  "Jakarta Barat",
  "Jakarta Utara",
  "Jakarta Timur",
  "Bandung",
  "Bekasi",
  "Bogor",
  "Depok",
  "Tangerang",
  "Tangerang Selatan",
  "Surabaya",
  "Sidoarjo",
  "Malang",
  "Semarang",
  "Yogyakarta",
  "Solo",
  "Medan",
  "Palembang",
  "Pekanbaru",
  "Padang",
  "Bandar Lampung",
  "Makassar",
  "Manado",
  "Denpasar",
  "Balikpapan",
  "Samarinda",
  "Pontianak",
  "Banjarmasin",
  "Batam",
  "Ambon",
  "Kupang",
  "Mataram",
  "Jayapura",
  "Banda Aceh",
  "Jambi",
  "Bengkulu",
  "Kendari",
] as const;

const MONTHS = [
  "Januari",
  "Februari",
  "Maret",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Agustus",
  "September",
  "Oktober",
  "November",
  "Desember",
] as const;

type Op = {
  slug: string;
  category: string;
  title: string;
  keywords: string[];
  summary: string;
  steps: string[];
  sla: string;
  channels: string[];
  exceptions: string[];
};

const OPS: Op[] = [
  {
    slug: "buka",
    category: "Akuisisi Produk",
    title: "Pembukaan fasilitas",
    keywords: ["buka", "pengajuan", "aktivasi", "onboarding"],
    summary: "Prosedur pembukaan fasilitas produk setelah CIF verified dan screening AML lulus.",
    steps: [
      "Pastikan CIF verified dan bukan DTTOT.",
      "Jelaskan fitur, biaya, dan risiko {produk}.",
      "Ambil persetujuan syarat & ketentuan.",
      "Booking fasilitas {produk} di core.",
      "Kirim notifikasi aktivasi ke HP/email terdaftar.",
    ],
    sla: "5-45 menit sesuai kanal",
    channels: ["Aplikasi Bang", "Cabang", "Video Banking"],
    exceptions: ["CIF update_required wajib refresh KYC dulu"],
  },
  {
    slug: "tutup",
    category: "Penutupan",
    title: "Penutupan fasilitas",
    keywords: ["tutup", "penutupan", "close", "nonaktif"],
    summary: "Penutupan {produk} hanya jika tidak ada outstanding, hold, atau linkage wajib.",
    steps: [
      "Cek outstanding, hold, autodebet, dan linkage {produk}.",
      "Selesaikan kewajiban tersisa.",
      "Tutup fasilitas di core.",
      "Terbitkan konfirmasi penutupan.",
    ],
    sla: "1 hari kerja",
    channels: ["Cabang", "Aplikasi Bang"],
    exceptions: ["Hold aparat/AML tidak boleh ditutup CS"],
  },
  {
    slug: "saldo",
    category: "Inquiry",
    title: "Inquiry saldo dan status",
    keywords: ["saldo", "inquiry", "cek status", "posisi"],
    summary: "CS menyampaikan posisi {produk} setelah otentikasi 3 data. Jangan sebut produk lain tanpa permintaan.",
    steps: [
      "Otentikasi CIF / rekening / 4 digit kartu + DOB + ibu kandung.",
      "Baca posisi available, hold, dan status {produk}.",
      "Jelaskan hold bila ada.",
    ],
    sla: "langsung",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Hold fraud eskalasi unit fraud"],
  },
  {
    slug: "mutasi",
    category: "Inquiry",
    title: "Inquiry mutasi dan statement",
    keywords: ["mutasi", "statement", "rekening koran", "riwayat"],
    summary: "Mutasi {produk} tersedia 10 tahun digital. CS merujuk hasil RAG transaksi, bukan mengarang.",
    steps: [
      "Tentukan periode.",
      "Ambil mutasi {produk} dari core/RAG.",
      "Kirim PDF ke email terdaftar bila diminta.",
    ],
    sla: "langsung 12 bulan, 1 hari kerja arsip > 1 tahun",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Periode > 10 tahun tidak tersedia"],
  },
  {
    slug: "limit",
    category: "Limit & Risiko",
    title: "Pengaturan limit",
    keywords: ["limit", "naikkan limit", "turunkan limit"],
    summary: "Perubahan limit {produk} wajib otentikasi. Kenaikan besar cooling-off 24 jam.",
    steps: [
      "Cek limit berjalan {produk}.",
      "Otentikasi PIN/OTP.",
      "Terapkan limit baru atau jadwalkan cooling-off.",
    ],
    sla: "langsung / 24 jam",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["CIF update_required tidak boleh naik limit"],
  },
  {
    slug: "biaya",
    category: "Biaya & Bunga",
    title: "Informasi biaya dan bunga",
    keywords: ["biaya", "admin", "bunga", "rate", "fee"],
    summary: "Gunakan board rate resmi {produk} pada hari ini. Jangan janji diskon di luar program.",
    steps: [
      "Buka tabel biaya {produk}.",
      "Sebut admin, bunga, denda, dan pajak.",
      "Tawarkan simulasi bila relevan.",
    ],
    sla: "langsung",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Promo mengikuti periode berlaku"],
  },
  {
    slug: "blokir",
    category: "Keamanan",
    title: "Blokir fasilitas",
    keywords: ["blokir", "freeze", "hot card", "nonaktifkan"],
    summary: "Blokir {produk} untuk mitigasi kehilangan, fraud, atau permintaan nasabah.",
    steps: [
      "Otentikasi cepat.",
      "Hot-block {produk}.",
      "Tinjau transaksi 24 jam terakhir.",
      "Tawarkan pengganti bila relevan.",
    ],
    sla: "< 3 menit",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Blokir hukum hanya Legal"],
  },
  {
    slug: "unblokir",
    category: "Keamanan",
    title: "Buka blokir fasilitas",
    keywords: ["unblokir", "buka blokir", "aktifkan lagi"],
    summary: "Unblokir {produk} setelah pastikan bukan hold fraud/aparat.",
    steps: [
      "Cek alasan blokir {produk}.",
      "Otentikasi kuat.",
      "Aktifkan kembali bila eligible.",
    ],
    sla: "15 menit",
    channels: ["Live CS", "Cabang"],
    exceptions: ["Hold AML/aparat tidak dibuka CS"],
  },
  {
    slug: "komplain",
    category: "Pengaduan",
    title: "Pengaduan produk",
    keywords: ["komplain", "pengaduan", "tiket", "ojk"],
    summary: "Setiap keluhan {produk} wajib tiket, ack 2 hari kerja, selesai 20 hari kerja.",
    steps: [
      "Dengarkan kronologi terkait {produk}.",
      "Buat tiket dan beri nomor.",
      "Klasifikasi dan eskalasi unit produk.",
    ],
    sla: "ack 2 hd, selesai 20 hd",
    channels: ["Live CS", "Email", "Cabang"],
    exceptions: ["Menunggu pihak ketiga dapat diperpanjang"],
  },
  {
    slug: "dispute",
    category: "Dispute",
    title: "Dispute transaksi",
    keywords: ["dispute", "tidak dikenali", "chargeback", "salah debet"],
    summary: "Dispute {produk} diajukan dengan bukti, RRN/reference, dan kronologi.",
    steps: [
      "Kunci transaksi tersangka pada {produk}.",
      "Minta bukti dan waktu.",
      "Ajukan ke switch/skema bila eligible.",
      "Informasikan SLA investigasi.",
    ],
    sla: "7-90 hari sesuai kanal",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Transaksi PIN lebih sulit di-chargeback"],
  },
  {
    slug: "reset-kredensial",
    category: "Keamanan",
    title: "Reset PIN atau kredensial",
    keywords: ["lupa pin", "reset pin", "ganti password"],
    summary: "Reset kredensial {produk} wajib otentikasi kuat. CS tidak menerima PIN baru secara lisan.",
    steps: [
      "Otentikasi CIF + DOB + ibu kandung + OTP.",
      "Kirim tautan reset {produk}.",
      "Nasabah membuat PIN baru di kanal resmi.",
    ],
    sla: "15 menit",
    channels: ["Aplikasi Bang", "Video Banking", "Live CS"],
    exceptions: ["3x salah PIN = blokir otomatis"],
  },
  {
    slug: "update-data",
    category: "CIF & Data",
    title: "Perubahan data yang tertaut produk",
    keywords: ["ubah data", "update", "ganti alamat", "ganti hp"],
    summary: "Perubahan data yang mempengaruhi {produk} dicatat di CIF history dan dinotifikasi.",
    steps: [
      "Otentikasi 2FA.",
      "Ubah data tertaut {produk}.",
      "Kirim notifikasi ke kontak lama dan baru.",
    ],
    sla: "langsung setelah OTP",
    channels: ["Aplikasi Bang", "Cabang"],
    exceptions: ["Ganti NIK/nama hanya proses Dukcapil"],
  },
  {
    slug: "asuransi",
    category: "Asuransi",
    title: "Asuransi terkait produk",
    keywords: ["asuransi", "klaim", "premi", "polis"],
    summary: "Jelaskan perlindungan yang menempel pada {produk} dan kanal klaim mitra.",
    steps: [
      "Cek status polis {produk}.",
      "Jelaskan manfaat dan pengecualian.",
      "Arahkan klaim ke panel bila terjadi peristiwa.",
    ],
    sla: "info langsung, klaim sesuai mitra",
    channels: ["Live CS", "Cabang"],
    exceptions: ["CS tidak menjanjikan hasil klaim"],
  },
  {
    slug: "pajak",
    category: "Pajak",
    title: "Perlakuan pajak produk",
    keywords: ["pajak", "pph", "bukti potong", "npwp"],
    summary: "Informasikan potongan pajak yang berlaku pada {produk} sesuai ketentuan tahun berjalan.",
    steps: [
      "Cek jenis penghasilan {produk}.",
      "Sebut tarif dan bukti potong.",
      "Unduh dokumen pajak bila tersedia.",
    ],
    sla: "langsung / Januari untuk tahun lalu",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["Restitusi bukan wewenang CS"],
  },
  {
    slug: "agunan",
    category: "Kredit",
    title: "Pengikatan dan pelepasan agunan",
    keywords: ["agunan", "jaminan", "roya", "bpkb", "shm"],
    summary: "Tata cara pengikatan atau pelepasan agunan yang terkait {produk}.",
    steps: [
      "Cek status agunan {produk}.",
      "Pastikan outstanding sebelum pelepasan.",
      "Proses roya/serah dokumen sesuai akad.",
    ],
    sla: "7-14 hari kerja setelah lunas",
    channels: ["Cabang"],
    exceptions: ["Sengketa agunan ditahan Legal"],
  },
  {
    slug: "restruk",
    category: "Kredit",
    title: "Restrukturisasi kewajiban",
    keywords: ["restruk", "keringanan", "tenor", "menunggak"],
    summary: "Restruk {produk} untuk nasabah kesulitan bayar, setelah evaluasi penghasilan.",
    steps: [
      "Isi form kesulitan {produk}.",
      "Simulasi angsuran baru.",
      "Akad addendum.",
    ],
    sla: "10 hari kerja",
    channels: ["Cabang"],
    exceptions: ["Hapus buku tidak masuk restruk standar"],
  },
  {
    slug: "pelunasan",
    category: "Kredit",
    title: "Pelunasan dipercepat",
    keywords: ["lunas", "pelunasan", "early repayment"],
    summary: "Hitung outstanding {produk} + bunga berjalan + penalty sesuai akad.",
    steps: [
      "Generate simpulan lunas {produk} berlaku 7 hari.",
      "Terima dana.",
      "Terbitkan surat lunas.",
    ],
    sla: "SKL 3 hari kerja",
    channels: ["Cabang", "Aplikasi Bang"],
    exceptions: ["Produk subsidi mengikuti aturan kementerian"],
  },
  {
    slug: "pencairan",
    category: "Kredit",
    title: "Pencairan fasilitas",
    keywords: ["pencairan", "disburse", "cair"],
    summary: "Pencairan {produk} ke rekening tujuan setelah akad dan checklist lengkap.",
    steps: [
      "Cek checklist akad {produk}.",
      "Validasi rekening tujuan.",
      "Eksekusi pencairan dan beri reference.",
    ],
    sla: "H+0 sampai H+3",
    channels: ["Cabang", "Aplikasi Bang"],
    exceptions: ["Pending legal/asuransi menunda cair"],
  },
  {
    slug: "subscription",
    category: "Wealth",
    title: "Subscription / pembelian",
    keywords: ["beli", "subscription", "order beli", "investasi"],
    summary: "Order beli {produk} mengikuti profil risiko dan cut-off pasar.",
    steps: [
      "Cek profil risiko vs {produk}.",
      "Debet rekening sumber.",
      "Kirim order ke mitra/MI.",
    ],
    sla: "T+0 sampai T+3",
    channels: ["Aplikasi Bang"],
    exceptions: ["Profil tidak sesuai wajib konfirmasi"],
  },
  {
    slug: "redemption",
    category: "Wealth",
    title: "Redemption / penjualan",
    keywords: ["jual", "redemption", "cair unit"],
    summary: "Order jual {produk} sebelum cut-off, settlement sesuai jenis fund.",
    steps: [
      "Cek unit tersedia {produk}.",
      "Kirim order jual.",
      "Kredit rekening sesuai settlement.",
    ],
    sla: "T+1 sampai T+3",
    channels: ["Aplikasi Bang"],
    exceptions: ["Force majeure pasar"],
  },
  {
    slug: "switching",
    category: "Wealth",
    title: "Switching instrumen",
    keywords: ["switching", "pindah fund", "alih"],
    summary: "Pindah dari/ke {produk} tanpa cair ke rekening, tetap memakai NAV masing-masing.",
    steps: [
      "Pilih sumber dan tujuan termasuk {produk}.",
      "Konfirmasi kenaikan risiko bila ada.",
      "Eksekusi switch.",
    ],
    sla: "T+2 sampai T+4",
    channels: ["Aplikasi Bang"],
    exceptions: ["Bancassurance tidak dapat di-switch"],
  },
  {
    slug: "transfer-out",
    category: "Transfer",
    title: "Transfer keluar",
    keywords: ["transfer", "kirim", "bi-fast", "rtgs"],
    summary: "Transfer dari rekening terkait {produk} mengikuti limit, cut-off, dan nama tujuan.",
    steps: [
      "Validasi tujuan dan limit {produk}.",
      "OTP/biometrik.",
      "Kirim dan simpan reference.",
    ],
    sla: "realtime s.d. H+1",
    channels: ["Aplikasi Bang", "ATM", "Cabang"],
    exceptions: ["Nama tidak match wajib konfirmasi risiko"],
  },
  {
    slug: "transfer-in",
    category: "Transfer",
    title: "Transfer masuk tertunda",
    keywords: ["transfer masuk", "belum masuk", "pending kredit"],
    summary: "Investigasi kredit masuk ke fasilitas terkait {produk} dengan reference pengirim.",
    steps: [
      "Minta jam, nominal, bank asal, reference.",
      "Cek inbound {produk}.",
      "Refund/rekon bila gagal di tengah.",
    ],
    sla: "1x24 jam auto, 3 hd manual",
    channels: ["Live CS"],
    exceptions: ["RTGS after cut-off H+1"],
  },
  {
    slug: "qris",
    category: "QRIS",
    title: "Pembayaran dan refund QRIS",
    keywords: ["qris", "scan", "refund qris"],
    summary: "QRIS yang tertaut {produk} realtime; refund hanya jika merchant/switch setuju.",
    steps: [
      "Cek RRN dan status settlement {produk}.",
      "Bila eligible, ajukan refund.",
      "Dana kembali 1-7 hari kerja.",
    ],
    sla: "bayar realtime, refund s.d. 7 hd",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["QR kadaluarsa tidak bisa dipaksa settle"],
  },
  {
    slug: "atm",
    category: "ATM",
    title: "Layanan ATM terkait produk",
    keywords: ["atm", "tarik tunai", "uang tidak keluar"],
    summary: "Penanganan tarik/setor ATM yang debet/kredit {produk}, termasuk gagal dispense.",
    steps: [
      "Minta lokasi ATM, jam, nominal.",
      "Cek journal vs core {produk}.",
      "Refund bila gagal dispense.",
    ],
    sla: "1x24 jam auto / 7 hd manual",
    channels: ["Live CS"],
    exceptions: ["ATM bank lain ikut aturan jaringan"],
  },
  {
    slug: "kartu-fisik",
    category: "Kartu",
    title: "Kartu fisik hilang rusak atau cetak ulang",
    keywords: ["kartu hilang", "kartu rusak", "cetak kartu"],
    summary: "Penggantian media fisik yang menaut {produk}: blokir, terbit baru, kirim ekspedisi.",
    steps: [
      "Blokir media lama {produk}.",
      "Terbit nomor baru atau same-number sesuai kebijakan.",
      "Kirim ke alamat CIF.",
    ],
    sla: "blokir langsung, kirim 3-7 hd",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Indikasi skimming wajib nomor baru"],
  },
  {
    slug: "autodebet",
    category: "Pembayaran",
    title: "Autodebet dan standing instruction",
    keywords: ["autodebet", "standing instruction", "tagihan otomatis"],
    summary: "Daftar/batal SI atau autodebet yang menarik {produk}.",
    steps: [
      "Cek biller dan tanggal tarik {produk}.",
      "Daftar atau batal H-1.",
      "Konfirmasi siklus berikutnya.",
    ],
    sla: "langsung, efektif siklus berikut",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["Tarikan hari ini tidak dapat ditarik mundur"],
  },
  {
    slug: "va",
    category: "Virtual Account",
    title: "Virtual account",
    keywords: ["virtual account", "va", "billing"],
    summary: "VA yang menaut {produk} closed/open amount; expired tidak di-settle manual CS.",
    steps: [
      "Cek nomor VA dan nominal {produk}.",
      "Konfirmasi status billing.",
      "Minta bayar ulang bila expired.",
    ],
    sla: "realtime / T+1 billing",
    channels: ["Aplikasi Bang", "ATM"],
    exceptions: ["Closed-amount harus exact"],
  },
  {
    slug: "dormant",
    category: "Simpanan",
    title: "Dormant dan aktivasi ulang",
    keywords: ["dormant", "tidak aktif", "aktivasi"],
    summary: "Fasilitas {produk} tanpa mutasi 12 bulan menjadi dormant.",
    steps: [
      "Cek mutasi terakhir {produk}.",
      "Setoran/aktivasi cabang.",
      "Refresh KYC bila perlu.",
    ],
    sla: "saat setoran / 1 hd cabang",
    channels: ["Cabang", "Aplikasi Bang"],
    exceptions: ["Dormant + high risk wajib cabang"],
  },
  {
    slug: "hold",
    category: "Operasi",
    title: "Hold dana atau fasilitas",
    keywords: ["hold", "tahan dana", "pending hold"],
    summary: "Hold pada {produk} karena AML, sita, atau investigasi. CS tidak tipping-off.",
    steps: [
      "Cek kode hold {produk}.",
      "Jelaskan secara umum dana belum available.",
      "Eskalasi unit pemilik hold.",
    ],
    sla: "eskalasi hari yang sama",
    channels: ["Live CS"],
    exceptions: ["Jangan sebut investigasi AML ke nasabah"],
  },
  {
    slug: "statement-pajak",
    category: "Dokumen",
    title: "Dokumen resmi dan surat keterangan",
    keywords: ["surat keterangan", "skn", "dokumen", "materai"],
    summary: "Penerbitan surat terkait {produk} melalui cabang atau e-statement.",
    steps: [
      "Pastikan identitas dan tujuan surat {produk}.",
      "Generate draft.",
      "Tanda tangani / e-sign.",
    ],
    sla: "1 hari kerja",
    channels: ["Cabang", "Aplikasi Bang"],
    exceptions: ["Surat untuk pengadilan via Legal"],
  },
  {
    slug: "limit-internasional",
    category: "Kartu",
    title: "Transaksi luar negeri dan e-commerce",
    keywords: ["luar negeri", "e-commerce", "internasional", "3ds"],
    summary: "Flag internasional/e-com pada {produk} dapat dimatikan untuk cegah fraud.",
    steps: [
      "Cek flag {produk}.",
      "Aktif/nonaktif sesuai permintaan.",
      "Ingatkan OTP 3DS tidak pernah diminta CS.",
    ],
    sla: "langsung",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["Kartu sudah hot-block harus ganti kartu"],
  },
  {
    slug: "cicilan",
    category: "Kartu",
    title: "Konversi cicilan",
    keywords: ["cicilan", "installment", "tenor belanja"],
    summary: "Konversi transaksi {produk} menjadi cicilan sesuai program tenor.",
    steps: [
      "Pilih transaksi eligible {produk}.",
      "Pilih tenor dan bunga.",
      "Berlaku di statement berikutnya.",
    ],
    sla: "statement berikutnya",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["Cash advance tidak dapat dicicil"],
  },
  {
    slug: "tagihan",
    category: "Kartu",
    title: "Tagihan dan jatuh tempo",
    keywords: ["tagihan", "jatuh tempo", "minimum payment"],
    summary: "CS menyampaikan total, minimum, bunga, dan due date {produk}.",
    steps: [
      "Otentikasi 4 digit terakhir bila kartu.",
      "Baca statement {produk}.",
      "Jelaskan konsekuensi bayar minimum.",
    ],
    sla: "langsung",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Status late: tawarkan rencana bayar"],
  },
  {
    slug: "kolektibilitas",
    category: "Kredit",
    title: "Kolektibilitas dan tunggakan",
    keywords: ["kolektibilitas", "tunggakan", "npl", "denda"],
    summary: "Penjelasan aging {produk} dan dampak SLIK bila menunggak.",
    steps: [
      "Sebut hari tunggak dan denda {produk}.",
      "Tawarkan bayar untuk cegah naik kol.",
      "Eskalasi collection bila perlu.",
    ],
    sla: "info langsung",
    channels: ["Live CS"],
    exceptions: ["Sudah di collection eksternal: jangan tawar diskon sendiri"],
  },
  {
    slug: "slik",
    category: "Kredit",
    title: "Dampak SLIK / BI checking",
    keywords: ["slik", "bi checking", "riwayat kredit"],
    summary: "Kinerja {produk} dilaporkan ke SLIK sesuai periode. CS tidak menghapus data SLIK.",
    steps: [
      "Jelaskan bahwa {produk} dilaporkan.",
      "Perbaikan muncul setelah bayar dan periode lapor.",
      "Arahkan pengajuan koreksi resmi bila sengketa.",
    ],
    sla: "info langsung",
    channels: ["Live CS", "Cabang"],
    exceptions: ["Koreksi SLIK bukan reset seketika"],
  },
  {
    slug: "kyc-produk",
    category: "CIF & KYC",
    title: "KYC khusus produk",
    keywords: ["kyc", "liveness", "dokumen tambahan"],
    summary: "Beberapa fitur {produk} butuh dokumen tambahan (NPWP, slip gaji, SIUP).",
    steps: [
      "Cek kelengkapan KYC {produk}.",
      "Minta dokumen kurang.",
      "Lanjutkan booking setelah lulus.",
    ],
    sla: "1-3 hari kerja",
    channels: ["Aplikasi Bang", "Cabang"],
    exceptions: ["PEP eskalasi Compliance"],
  },
  {
    slug: "device",
    category: "Aplikasi",
    title: "Device binding terkait produk",
    keywords: ["device binding", "ganti hp", "perangkat baru"],
    summary: "Perangkat baru membatasi transaksi berisiko pada {produk} sampai binding selesai.",
    steps: [
      "OTP ke HP terdaftar.",
      "Ikat perangkat.",
      "Cabut perangkat lama.",
    ],
    sla: "10 menit",
    channels: ["Aplikasi Bang", "Live CS"],
    exceptions: ["HP hilang: ganti nomor dulu"],
  },
  {
    slug: "fraud",
    category: "Keamanan & Fraud",
    title: "Indikasi fraud pada produk",
    keywords: ["fraud", "phishing", "penipuan", "otp bocor"],
    summary: "Jika ada indikasi penyalahgunaan {produk}, blokir kanal dan buka tiket fraud.",
    steps: [
      "Blokir {produk} dan kanal terkait.",
      "Ganti kredensial.",
      "Catat kronologi, jangan minta OTP.",
    ],
    sla: "blokir langsung",
    channels: ["Live CS"],
    exceptions: ["CS tidak pernah minta OTP/PIN"],
  },
  {
    slug: "promo",
    category: "Promo",
    title: "Program promo dan cashback",
    keywords: ["promo", "cashback", "reward", "diskon"],
    summary: "Syarat promo {produk} mengikuti periode, MCC, dan settle transaksi.",
    steps: [
      "Cek periode promo {produk}.",
      "Jelaskan MCC/exclude.",
      "Cashback posting sesuai SLA program.",
    ],
    sla: "info langsung, posting H+3 s.d. akhir bulan",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Tunai/transfer biasanya exclude"],
  },
  {
    slug: "limit-harian",
    category: "Limit & Risiko",
    title: "Limit harian dan cooling-off",
    keywords: ["limit harian", "cooling off", "transaksi ditolak"],
    summary: "Transaksi {produk} ditolak jika menembus limit harian/per transaksi.",
    steps: [
      "Cek pemakaian limit {produk} hari ini.",
      "Jelaskan sisa limit.",
      "Tawarkan kenaikan sesuai kebijakan.",
    ],
    sla: "langsung",
    channels: ["Live CS", "Aplikasi Bang"],
    exceptions: ["Cooling-off 24 jam untuk kenaikan besar"],
  },
  {
    slug: "notifikasi",
    category: "Aplikasi",
    title: "Notifikasi transaksi",
    keywords: ["notifikasi", "sms", "push", "email alert"],
    summary: "Setiap mutasi {produk} memicu alert sesuai preferensi nasabah.",
    steps: [
      "Cek kanal notifikasi {produk}.",
      "Aktifkan push/SMS/email.",
      "Uji dengan transaksi kecil bila perlu.",
    ],
    sla: "langsung",
    channels: ["Aplikasi Bang"],
    exceptions: ["SMS berbayar sesuai paket"],
  },
  {
    slug: "waris",
    category: "Legal",
    title: "Ahli waris dan blokir meninggal",
    keywords: ["ahli waris", "meninggal", "akta kematian"],
    summary: "Jika pemilik {produk} meninggal, blokir lalu proses ke ahli waris.",
    steps: [
      "Terima akta kematian.",
      "Blokir {produk}.",
      "Hitung hak/kewajiban.",
      "Bayarkan sesuai surat waris.",
    ],
    sla: "14 hari kerja setelah dokumen lengkap",
    channels: ["Cabang"],
    exceptions: ["Sengketa waris ditahan"],
  },
  {
    slug: "valas",
    category: "Valas",
    title: "Konversi valas",
    keywords: ["valas", "usd", "kurs", "tukar"],
    summary: "Konversi terkait {produk} memakai kurs digital hari kerja + spread.",
    steps: [
      "Cek ketersediaan valas {produk}.",
      "Quotation kurs.",
      "Eksekusi sebelum quotation expire.",
    ],
    sla: "hari kerja, quotation singkat",
    channels: ["Aplikasi Bang", "Cabang"],
    exceptions: ["Akhir pekan mengikuti kurs terakhir + flag"],
  },
  {
    slug: "swift",
    category: "Transfer",
    title: "Transfer SWIFT / luar negeri",
    keywords: ["swift", "luar negeri", "wire", "remittance"],
    summary: "Outgoing internasional dari rekening terkait {produk} butuh SWIFT code dan tujuan dana.",
    steps: [
      "Lengkapi beneficiary dan tujuan dana {produk}.",
      "Cut-off 11.00 WIB.",
      "Beritahu kemungkinan full-amount/charge OUR/SHA.",
    ],
    sla: "H+0 s.d. H+2",
    channels: ["Cabang"],
    exceptions: ["Negara sanctioned ditolak"],
  },
  {
    slug: "payroll",
    category: "SME",
    title: "Payroll dan bulk payment",
    keywords: ["payroll", "bulk", "gaji", "mass transfer"],
    summary: "Bulk payment dari {produk} giro/usaha mengikuti file H-1.",
    steps: [
      "Unggah file payroll dari {produk}.",
      "Validasi rekening tujuan.",
      "Eksekusi H+0 pagi.",
    ],
    sla: "file H-1 pukul 16.00",
    channels: ["Aplikasi Bang", "Cabang"],
    exceptions: ["Rekening tujuan salah ditolak baris"],
  },
  {
    slug: "escrow",
    category: "SME",
    title: "Escrow dan rekening khusus",
    keywords: ["escrow", "rekening khusus", "developer"],
    summary: "Penggunaan {produk} sebagai escrow hanya untuk mitra dengan akad terpisah.",
    steps: [
      "Cek akad escrow {produk}.",
      "Release sesuai milestone.",
      "Tidak bisa di-override CS.",
    ],
    sla: "sesuai akad",
    channels: ["Cabang"],
    exceptions: ["Bukan mitra: tolak"],
  },
];

const CITY_SERVICES = [
  ["lokasi KC", "Kantor cabang", "Jam KC 08.00-15.00 hari kerja. Appointment prioritas di aplikasi."],
  ["lokasi KCP", "Kantor cabang pembantu", "KCP melayani teller dan CS, tanpa safe deposit."],
  ["lokasi ATM", "ATM 24 jam", "ATM/CRM 24 jam di mal dan area perkantoran."],
  ["setoran crm", "CRM setor tunai", "Setor kelipatan Rp 50.000, kredit realtime rekening sendiri."],
  ["safe deposit", "Safe deposit box", "SDB tahunan, akses KTP + specimen, stok terbatas."],
  ["prioritas lounge", "Layanan prioritas", "Nasabah priority dapat lounge dan CS dedicated."],
  ["ganti kartu onsite", "Cetak kartu di cabang", "Kartu darurat same-day di KC tertentu."],
  ["video banking booth", "Booth video banking", "Booth untuk KYC dan unblokir tanpa antrian teller."],
] as const;

const SEASONAL = [
  ["THR dan arus gaji", "Siapkan limit dan hold gaji. Antrian ATM naik."],
  ["Periode laporan pajak", "Bukti potong bunga dan unduh statement tahunan."],
  ["Libur panjang", "Cabang tutup, ATM/QRIS/BI-FAST tetap 24 jam."],
  ["Promo 11-11 / 12-12", "Naikkan monitoring fraud e-com dan 3DS."],
  ["Pembayaran UKT/sekolah", "Siapkan VA dan limit transfer pendidikan."],
  ["Pembayaran PBB/pajak daerah", "Biller pajak daerah cut-off mengikuti PEMDA."],
  ["Arus mudik", "Naikkan limit tarik tunai sementara dengan cooling-off pendek."],
  ["Tutup buku tahunan", "Statement Desember dan bunga mengendap diposting awal Januari."],
  ["Pembagian dividen reksa", "NAV dan dividen fund dipublikasikan H+1 bursa."],
  ["Cicilan masuk tahun ajaran", "Kenaikan pengajuan KTA/Paylater; cek DBR."],
  ["Perpanjangan STNK", "Autodebet Samsat dan denda bila gagal debet."],
  ["Program CSR/zakat", "Transfer ke Lembaga Amil resmi, bukti ke email."],
] as const;

function fill(template: string, product: string): string {
  return template.replaceAll("{produk}", product);
}

export function expandSops(): SopDocument[] {
  const docs: SopDocument[] = [];
  let n = 1;
  const nextId = (prefix: string) => `SOP-${prefix}-${String(n++).padStart(4, "0")}`;

  for (const product of PRODUCTS) {
    for (const op of OPS) {
      docs.push({
        id: nextId("GEN"),
        category: op.category,
        title: `${op.title} ${product}`,
        keywords: [...op.keywords, product.toLowerCase(), ...product.toLowerCase().split(" ")],
        summary: fill(op.summary, product),
        steps: op.steps.map((s) => fill(s, product)),
        sla: op.sla,
        channels: op.channels,
        exceptions: op.exceptions.map((s) => fill(s, product)),
        products: [product],
      });
    }
  }

  const segmentOps = OPS.filter((o) =>
    ["limit", "biaya", "blokir", "saldo", "mutasi", "komplain", "tagihan", "kolektibilitas", "kyc-produk", "limit-harian"].includes(o.slug),
  );
  for (const product of PRODUCTS) {
    for (const op of segmentOps) {
      for (const segment of SEGMENTS) {
        docs.push({
          id: nextId("SEG"),
          category: `${op.category} · Segmen`,
          title: `${op.title} ${product} untuk segmen ${segment}`,
          keywords: [...op.keywords, product.toLowerCase(), segment, "segmen"],
          summary: `${fill(op.summary, product)} Penyesuaian kebijakan untuk segmen ${segment}.`,
          steps: [
            `Identifikasi segmen nasabah: ${segment}.`,
            ...op.steps.map((s) => fill(s, product)),
            `Catat bahwa threshold ${segment} berbeda dari segmen lain.`,
          ],
          sla: op.sla,
          channels: op.channels,
          exceptions: [`Kebijakan ${segment} tidak boleh dipakai untuk segmen lain`, ...op.exceptions],
          products: [product],
        });
      }
    }
  }

  for (const city of CITIES) {
    for (const [kw, title, summary] of CITY_SERVICES) {
      docs.push({
        id: nextId("LOC"),
        category: "Cabang & Lokasi",
        title: `${title} Bang Digital ${city}`,
        keywords: [kw, "lokasi", "cabang", "atm", city.toLowerCase()],
        summary: `${summary} Lokasi acuan: ${city}.`,
        steps: [
          `Verifikasi kota nasabah: ${city}.`,
          `Berikan opsi ${title} terdekat di ${city}.`,
          "Sebut jam layanan dan apakah perlu appointment.",
        ],
        sla: "langsung",
        channels: ["Live CS", "Aplikasi Bang"],
        exceptions: ["Libur nasional cabang tutup, ATM tetap 24 jam"],
        products: [],
      });
    }
  }

  for (const month of MONTHS) {
    for (const [title, summary] of SEASONAL) {
      docs.push({
        id: nextId("CAL"),
        category: "Kalender Operasional",
        title: `Prosedur CS ${title} — ${month}`,
        keywords: [month.toLowerCase(), ...title.toLowerCase().split(" "), "kalender", "operasional"],
        summary: `Fokus layanan bulan ${month}: ${summary}`,
        steps: [
          `Cek kalender operasional ${month}.`,
          summary,
          "Sampaikan ETA realistis kepada nasabah.",
          "Eskalasi bila volume insiden naik.",
        ],
        sla: "mengikuti SLA produk terkait",
        channels: ["Live CS"],
        exceptions: ["Insiden nasional: gunakan skrip resmi operasi"],
        products: [],
      });
    }
  }

  return docs;
}
